#!/usr/bin/env python3
"""
FocusLearner Pro - Environment Setup Script
Helps set up development environment with required environment variables
"""

import os
import sys
from pathlib import Path


def create_env_file():
    """Create .env file from template if it doesn't exist"""
    env_file = Path('.env')
    env_example = Path('env.example')
    
    if env_file.exists():
        print("✓ .env file already exists")
        return True
    
    # Try to read from env.example if it exists
    template_vars = {}
    if env_example.exists():
        with open(env_example, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key = line.split('=')[0].strip()
                    value = line.split('=', 1)[1].strip()
                    template_vars[key] = value
    
    # Default values
    default_vars = {
        'FLASK_ENV': 'development',
        'FLASK_DEBUG': 'True',
        'SECRET_KEY': 'dev-secret-key-change-in-production',
        'JWT_SECRET_KEY': 'dev-jwt-secret-key-change-in-production',
        'DATABASE_URL': 'sqlite:///focuslearner_v3.db',
        'GOOGLE_API_KEY': '',
        'YOUTUBE_API_KEY': '',
        'LOG_LEVEL': 'INFO',
        'CORS_ORIGINS': 'http://localhost:3000,http://localhost:3001',
    }
    
    # Merge template and defaults
    env_vars = {**default_vars, **template_vars}
    
    # Write .env file
    with open(env_file, 'w') as f:
        f.write("# FocusLearner Pro Environment Variables\n")
        f.write("# Generated by setup script\n\n")
        
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    print("✓ Created .env file with default values")
    print("⚠ Please update .env file with your actual API keys and secrets")
    return True


def check_dependencies():
    """Check if required dependencies are installed"""
    try:
        import flask
        import flask_sqlalchemy
        import flask_cors
        print("✓ Core dependencies are installed")
        return True
    except ImportError as e:
        print(f"✗ Missing dependency: {e.name}")
        print("  Run: pip install -r requirements.txt")
        return False


def check_database():
    """Check database connection"""
    try:
        from models import db
        from app import app
        
        with app.app_context():
            # Try to connect
            db.session.execute(db.text('SELECT 1'))
            print("✓ Database connection successful")
            return True
    except Exception as e:
        print(f"⚠ Database connection issue: {e}")
        print("  This is normal if database hasn't been created yet")
        return False


def main():
    """Main setup function"""
    print("FocusLearner Pro - Environment Setup")
    print("=" * 40)
    
    # Change to backend directory if running from root
    if Path('backend').exists() and not Path('app.py').exists():
        os.chdir('backend')
        print("Changed to backend directory")
    
    print("\n1. Checking environment file...")
    create_env_file()
    
    print("\n2. Checking dependencies...")
    if not check_dependencies():
        sys.exit(1)
    
    print("\n3. Checking database...")
    check_database()
    
    print("\n" + "=" * 40)
    print("Setup complete!")
    print("\nNext steps:")
    print("1. Update .env file with your API keys")
    print("2. Run: python app.py")
    print("3. Visit: http://localhost:5000/api/health")


if __name__ == '__main__':
    main()
